# Generated by Django 5.2.1 on 2025-05-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_interviewanalysis_sentiment_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewanalysis',
            name='emotion_scores',
            field=models.JSONField(default=dict),
        ),
    ]
