# Generated by Django 5.2.1 on 2025-05-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_interviewanalysis_emotion_scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewanalysis',
            name='pause_analytics',
            field=models.JSONField(default=dict),
        ),
    ]
