# Generated by Django 5.2.1 on 2025-05-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_interviewanalysis_pause_analytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewanalysis',
            name='interview_score',
            field=models.FloatField(default=0.0, help_text='Overall interview performance score'),
        ),
    ]
